name: lucidplus_chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bubble: ^1.2.1
  build_runner: ^2.3.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.5
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_storage: ^11.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_intl: ^0.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_screenutil: ^5.7.0
  flutter_secure_storage: ^7.0.1
  flutter_svg: null
  fluttertoast: ^8.2.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  http_parser: ^4.0.2
  image_picker: ^0.8.7+5
  injectable: ^1.5.3
  injectable_generator: ^1.5.3
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
